version: 2.1

orbs:
  node: medpeer/rails@1.2.0

executors:
  ruby:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
      - image: circleci/postgres
  ruby_with_db:
    docker:
      - image: *docker_ruby
      - image: circleci/postgres:12.4-ram
    environment:
      DATABSE_URL: 'postgres://postgres:postgres@127.0.0.1:5432'

jobs:
  rubocop:
    executor: ruby
    steps:
      - checkout

      - rails/bundle-install:
          restore_only: true

      - run: bundle exec rubocop --parallel

workflows:
  rspec:
    jobs:
      - rails/rb-deps:
          executor: ruby
      - rails/js-deps:
          executor: ruby
      - rails/assets:
          executor: ruby
          requires:
            - rails/rb-deps
            - rails/js-deps
      - rubocop:
          requires:
            - rails/rb-deps
      - rails/rspec:
          executor: ruby_with_db
          db-port: '5432'
          requires:
            - rails/assets
