default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
  
development:
  <<: *default
  database: tamtim_development

test:
  <<: *default
  database: tamtim_test

production:
  <<: *default
  database: tamtim_production
  username: tamtim
  password: <%= ENV['TAMTIM_DATABASE_PASSWORD'] %>
